// Generated by scripts/seed_from_questionnaire_example.mjs
const dbName = "appdev";
const dbRef = db.getSiblingDB(dbName);
const now = new Date();

// Cleanup existing questionnaire by slug
const existing = dbRef.Questionnaire.findOne({ slug: "questionnaire-exemple" }, { _id: 1 });
if (existing) {
  const domainIds = dbRef.Domain.find({ questionnaireId: existing._id }, { _id: 1 }).toArray().map(d => d._id);
  const questionIds = dbRef.Question.find({ domainId: { $in: domainIds } }, { _id: 1 }).toArray().map(q => q._id);
  if (questionIds.length) dbRef.AnswerOption.deleteMany({ questionId: { $in: questionIds } });
  if (domainIds.length) dbRef.Resource.deleteMany({ domainId: { $in: domainIds } });
  if (domainIds.length) dbRef.Question.deleteMany({ domainId: { $in: domainIds } });
  if (domainIds.length) dbRef.Domain.deleteMany({ _id: { $in: domainIds } });
  dbRef.Questionnaire.deleteOne({ _id: existing._id });
}

// Questionnaire
const questionnaire = dbRef.Questionnaire.insertOne({
  title: "Questionnaire exemple",
  description: "Importé depuis QuestionnaireExemple.md",
  slug: "questionnaire-exemple",
  status: "published",
  createdAt: now,
  updatedAt: now,
});

// Domains, Resources, Questions, Answers
const domain1 = dbRef.Domain.insertOne({
  questionnaireId: questionnaire.insertedId,
  name: "Conception & structuration",
  description: "DESIGN",
  order: 1,
  createdAt: now,
  updatedAt: now,
});
dbRef.Resource.insertOne({
  domainId: domain1.insertedId,
  title: "Support DESIGN",
  type: "pptx",
  url: "http://localhost:3000/CM_DESIGN.pptx",
  order: 1,
});
const q_1_1 = dbRef.Question.insertOne({
  domainId: domain1.insertedId,
  type: "single-choice",
  prompt: "Objectifs et plan de séance sont :",
  helpText: "",
  order: 1,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_1.insertedId,
  value: "A",
  label: "Explicites (annoncés + rappel en cours)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_1.insertedId,
  value: "B",
  label: "Présents mais irréguliers (annoncés ou rappelés parfois)",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_1.insertedId,
  value: "C",
  label: "Plutôt implicites / seulement dans le syllabus",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_1.insertedId,
  value: "D",
  label: "Peu ou pas formalisés",
  score: 1,
  order: 4,
});

const q_1_2 = dbRef.Question.insertOne({
  domainId: domain1.insertedId,
  type: "single-choice",
  prompt: "Votre séance est organisée en :",
  helpText: "",
  order: 2,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_2.insertedId,
  value: "A",
  label: "Blocs courts (10–15 min) avec jalons/transitions",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_2.insertedId,
  value: "B",
  label: "Quelques grandes parties (20–30 min) avec transitions",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_2.insertedId,
  value: "C",
  label: "Exposé plutôt linéaire avec peu de jalons",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_2.insertedId,
  value: "D",
  label: "Structure très variable / improvisée",
  score: 1,
  order: 4,
});

const q_1_3 = dbRef.Question.insertOne({
  domainId: domain1.insertedId,
  type: "single-choice",
  prompt: "Vos supports (slides/notes) servent surtout à :",
  helpText: "",
  order: 3,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_3.insertedId,
  value: "A",
  label: "Faciliter l’attention (visuels, peu de texte) + compléments à part",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_3.insertedId,
  value: "B",
  label: "Mélange équilibré (texte synthétique + visuels)",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_3.insertedId,
  value: "C",
  label: "Être “autoportants” (beaucoup de texte)",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_3.insertedId,
  value: "D",
  label: "Remplacer le cours (très détaillés / lecture)",
  score: 1,
  order: 4,
});

const q_1_4 = dbRef.Question.insertOne({
  domainId: domain1.insertedId,
  type: "single-choice",
  prompt: "Exemples / applications / cas :",
  helpText: "",
  order: 4,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_4.insertedId,
  value: "A",
  label: "À chaque notion clé",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_4.insertedId,
  value: "B",
  label: "Régulièrement (plusieurs fois par CM)",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_4.insertedId,
  value: "C",
  label: "Occasionnellement",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_1_4.insertedId,
  value: "D",
  label: "Rarement",
  score: 1,
  order: 4,
});

const domain2 = dbRef.Domain.insertOne({
  questionnaireId: questionnaire.insertedId,
  name: "Animation & dynamique",
  description: "DYNAMIQUE",
  order: 2,
  createdAt: now,
  updatedAt: now,
});
dbRef.Resource.insertOne({
  domainId: domain2.insertedId,
  title: "Support DYNAMIQUE",
  type: "pptx",
  url: "http://localhost:3000/CM_DYNAMIQUE.pptx",
  order: 1,
});
const q_2_1 = dbRef.Question.insertOne({
  domainId: domain2.insertedId,
  type: "single-choice",
  prompt: "Le rythme en séance (typique) est :",
  helpText: "",
  order: 1,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_1.insertedId,
  value: "A",
  label: "Alternance régulière (exposé ↔ relance/mini-activité)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_1.insertedId,
  value: "B",
  label: "Majoritairement exposé + 1–2 relances",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_1.insertedId,
  value: "C",
  label: "Exposé continu avec quelques questions ponctuelles",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_1.insertedId,
  value: "D",
  label: "Exposé continu",
  score: 1,
  order: 4,
});

const q_2_2 = dbRef.Question.insertOne({
  domainId: domain2.insertedId,
  type: "single-choice",
  prompt: "Vous rendez l’utilité et les points clés visibles :",
  helpText: "",
  order: 2,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_2.insertedId,
  value: "A",
  label: "Très souvent (signaux, reformulations, synthèses intermédiaires)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_2.insertedId,
  value: "B",
  label: "Souvent mais pas systématique",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_2.insertedId,
  value: "C",
  label: "Parfois",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_2.insertedId,
  value: "D",
  label: "Rarement",
  score: 1,
  order: 4,
});

const q_2_3 = dbRef.Question.insertOne({
  domainId: domain2.insertedId,
  type: "single-choice",
  prompt: "Gestion du temps (fin de séance, équilibre) :",
  helpText: "",
  order: 3,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_3.insertedId,
  value: "A",
  label: "Maîtrisée (respect global du scénario)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_3.insertedId,
  value: "B",
  label: "Petits écarts (≤ 10 min)",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_3.insertedId,
  value: "C",
  label: "Écarts fréquents (trop long/trop court)",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_2_3.insertedId,
  value: "D",
  label: "Très variable / difficile à tenir",
  score: 1,
  order: 4,
});

const domain3 = dbRef.Domain.insertOne({
  questionnaireId: questionnaire.insertedId,
  name: "Interactivité légère",
  description: "MICRO",
  order: 3,
  createdAt: now,
  updatedAt: now,
});
dbRef.Resource.insertOne({
  domainId: domain3.insertedId,
  title: "Support MICRO",
  type: "pptx",
  url: "http://localhost:3000/CM_MICRO.pptx",
  order: 1,
});
const q_3_1 = dbRef.Question.insertOne({
  domainId: domain3.insertedId,
  type: "single-choice",
  prompt: "Fréquence des interactions courtes (question/vote/écrit) :",
  helpText: "",
  order: 1,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_1.insertedId,
  value: "A",
  label: "Toutes les 10–15 min",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_1.insertedId,
  value: "B",
  label: "2–3 fois par séance",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_1.insertedId,
  value: "C",
  label: "1 fois par séance",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_1.insertedId,
  value: "D",
  label: "Rarement / jamais",
  score: 1,
  order: 4,
});

const q_3_2 = dbRef.Question.insertOne({
  domainId: domain3.insertedId,
  type: "single-choice",
  prompt: "Modalité la plus fréquente pour faire répondre :",
  helpText: "",
  order: 2,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_2.insertedId,
  value: "A",
  label: "Vote (main levée / outil) ou écrit rapide (30–90s)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_2.insertedId,
  value: "B",
  label: "Discussion à deux (1–2 min) puis retour",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_2.insertedId,
  value: "C",
  label: "Réponse orale volontaire uniquement",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_2.insertedId,
  value: "D",
  label: "Je fais peu répondre",
  score: 1,
  order: 4,
});

const q_3_3 = dbRef.Question.insertOne({
  domainId: domain3.insertedId,
  type: "single-choice",
  prompt: "Recueil des questions étudiantes :",
  helpText: "",
  order: 3,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_3.insertedId,
  value: "A",
  label: "Continu + possible anonymat (outil/papier)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_3.insertedId,
  value: "B",
  label: "Principalement à l’oral en cours",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_3.insertedId,
  value: "C",
  label: "Surtout en fin de séance",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_3_3.insertedId,
  value: "D",
  label: "Rarement / jamais",
  score: 1,
  order: 4,
});

const domain4 = dbRef.Domain.insertOne({
  questionnaireId: questionnaire.insertedId,
  name: "Apprentissage actif",
  description: "ACTIVE",
  order: 4,
  createdAt: now,
  updatedAt: now,
});
dbRef.Resource.insertOne({
  domainId: domain4.insertedId,
  title: "Support ACTIVE",
  type: "pptx",
  url: "http://localhost:3000/CM_ACTIVE.pptx",
  order: 1,
});
const q_4_1 = dbRef.Question.insertOne({
  domainId: domain4.insertedId,
  type: "single-choice",
  prompt: "Part du temps où les étudiants “font” (écrire, résoudre, discuter) :",
  helpText: "",
  order: 1,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_1.insertedId,
  value: "A",
  label: "≥ 20%",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_1.insertedId,
  value: "B",
  label: "10–19%",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_1.insertedId,
  value: "C",
  label: "1–9%",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_1.insertedId,
  value: "D",
  label: "0%",
  score: 1,
  order: 4,
});

const q_4_2 = dbRef.Question.insertOne({
  domainId: domain4.insertedId,
  type: "single-choice",
  prompt: "Activité la plus fréquente (si vous en faites) :",
  helpText: "",
  order: 2,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_2.insertedId,
  value: "A",
  label: "Quiz conceptuel + discussion (vote → échange → revote)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_2.insertedId,
  value: "B",
  label: "Mini-exercice individuel écrit (1–3 min)",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_2.insertedId,
  value: "C",
  label: "Cas/problème en groupes (10–20 min)",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_2.insertedId,
  value: "D",
  label: "Aucune",
  score: 1,
  order: 4,
});

const q_4_3 = dbRef.Question.insertOne({
  domainId: domain4.insertedId,
  type: "single-choice",
  prompt: "Votre principal frein à l’apprentissage actif en amphi :",
  helpText: "",
  order: 3,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_3.insertedId,
  value: "A",
  label: "Manque de scénarios adaptés (idées prêtes à l’emploi)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_3.insertedId,
  value: "B",
  label: "Gestion temps/bruit/contrôle",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_3.insertedId,
  value: "C",
  label: "Logistique/taille du groupe",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_4_3.insertedId,
  value: "D",
  label: "Pas d’intérêt / pas prioritaire",
  score: 1,
  order: 4,
});

const domain5 = dbRef.Domain.insertOne({
  questionnaireId: questionnaire.insertedId,
  name: "Évaluation formative & adaptation",
  description: "FEEDBACK",
  order: 5,
  createdAt: now,
  updatedAt: now,
});
dbRef.Resource.insertOne({
  domainId: domain5.insertedId,
  title: "Support FEEDBACK",
  type: "pptx",
  url: "http://localhost:3000/CM_FEEDBACK.pptx",
  order: 1,
});
const q_5_1 = dbRef.Question.insertOne({
  domainId: domain5.insertedId,
  type: "single-choice",
  prompt: "Vérification de compréhension pendant le CM :",
  helpText: "",
  order: 1,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_1.insertedId,
  value: "A",
  label: "Structurée et fréquente (diagnostics planifiés)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_1.insertedId,
  value: "B",
  label: "Présente mais plutôt “au feeling”",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_1.insertedId,
  value: "C",
  label: "Occasionnelle",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_1.insertedId,
  value: "D",
  label: "Rare / jamais",
  score: 1,
  order: 4,
});

const q_5_2 = dbRef.Question.insertOne({
  domainId: domain5.insertedId,
  type: "single-choice",
  prompt: "Méthode principale pour repérer les incompréhensions :",
  helpText: "",
  order: 2,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_2.insertedId,
  value: "A",
  label: "Quiz/sondage ou mini-écrit (“point flou”)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_2.insertedId,
  value: "B",
  label: "Questions ciblées avec justification",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_2.insertedId,
  value: "C",
  label: "Signaux informels (“ça va ?”, regards)",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_2.insertedId,
  value: "D",
  label: "Je n’ai pas de méthode claire",
  score: 1,
  order: 4,
});

const q_5_3 = dbRef.Question.insertOne({
  domainId: domain5.insertedId,
  type: "single-choice",
  prompt: "Ajustement en direct quand un diagnostic est mauvais :",
  helpText: "",
  order: 3,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_3.insertedId,
  value: "A",
  label: "Oui, souvent (je re-séquence / reviens / change d’exemple)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_3.insertedId,
  value: "B",
  label: "Parfois",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_3.insertedId,
  value: "C",
  label: "Rarement (manque de temps)",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_5_3.insertedId,
  value: "D",
  label: "Jamais / je ne sais pas comment",
  score: 1,
  order: 4,
});

const domain6 = dbRef.Domain.insertOne({
  questionnaireId: questionnaire.insertedId,
  name: "Outils & environnement",
  description: "TECH",
  order: 6,
  createdAt: now,
  updatedAt: now,
});
dbRef.Resource.insertOne({
  domainId: domain6.insertedId,
  title: "Support TECH",
  type: "pptx",
  url: "http://localhost:3000/CM_TECH.pptx",
  order: 1,
});
const q_6_1 = dbRef.Question.insertOne({
  domainId: domain6.insertedId,
  type: "single-choice",
  prompt: "Confort avec un outil d’interaction (Wooclap/Menti/Kahoot…) :",
  helpText: "",
  order: 1,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_1.insertedId,
  value: "A",
  label: "À l’aise (je scénarise des séquences)",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_1.insertedId,
  value: "B",
  label: "Je sais l’utiliser simplement",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_1.insertedId,
  value: "C",
  label: "J’ai peu essayé / je ne suis pas sûr",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_1.insertedId,
  value: "D",
  label: "Je n’utilise pas et préfère éviter",
  score: 1,
  order: 4,
});

const q_6_2 = dbRef.Question.insertOne({
  domainId: domain6.insertedId,
  type: "single-choice",
  prompt: "Organisation/accès aux ressources (LMS, supports) :",
  helpText: "",
  order: 2,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_2.insertedId,
  value: "A",
  label: "Centralisé, clair, facile d’accès",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_2.insertedId,
  value: "B",
  label: "Plutôt organisé mais perfectible",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_2.insertedId,
  value: "C",
  label: "Dispersé / pas lisible",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_2.insertedId,
  value: "D",
  label: "Très minimal / peu diffusé",
  score: 1,
  order: 4,
});

const q_6_3 = dbRef.Question.insertOne({
  domainId: domain6.insertedId,
  type: "single-choice",
  prompt: "Volonté de tester (si on vous donne un scénario clé en main) :",
  helpText: "",
  order: 3,
  isRequired: true,
  createdAt: now,
  updatedAt: now,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_3.insertedId,
  value: "A",
  label: "Oui, dès la prochaine séance",
  score: 4,
  order: 1,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_3.insertedId,
  value: "B",
  label: "Oui, avec accompagnement",
  score: 3,
  order: 2,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_3.insertedId,
  value: "C",
  label: "Peut-être",
  score: 2,
  order: 3,
});
dbRef.AnswerOption.insertOne({
  questionId: q_6_3.insertedId,
  value: "D",
  label: "Peu probable",
  score: 1,
  order: 4,
});


print("Seed terminé");